name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: 
        cd S4\Arturo\Actividades\Act1-1
        ./configure
    - name: make
      run: 
        cd S4\Arturo\Actividades\Act1-1
        make
    - name: make check
      run: 
        cd S4\Arturo\Actividades\Act1-1
        make check
    - name: make distcheck
      run: 
        cd S4\Arturo\Actividades\Act1-1
        make distcheck
