name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up C++ environment
      run: sudo apt-get install -y build-essential
    - name: Compile the project
      run: |
        cd S4/Arturo/Actividades/Act1-1
        make
    - name: Run the project
      run: |
        cd S4/Arturo/Actividades/Act1-1
        ./your_executable_name
